version: 2

project_name: vidforge

before:
  hooks:
    - go mod tidy
    - bash scripts/download-binaries.sh

builds:
  - id: vidforge
    main: ./cmd/vidforge
    binary: vidforge
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  disable: true

brews:
  - name: vidforge
    homepage: https://github.com/Abhi1264/vidforge
    description: Terminal-based universal video downloader
    license: MIT

    repository:
      owner: Abhi1264
      name: homebrew-tap

    install: |
      bin.install "vidforge"

    test: |
      system "#{bin}/vidforge", "--help"
